### ISSUE TITLE
z-index usage interferes with paper-elements such as paper-scroll-header-panel

### ISSUE THREAD

**Issue by ktiedt** [vaadin/components#83] opened 2015-08-14 22:39 UTC
I am testing v-grid inside the polymer-starter-kit and I noticed the v-grid has a z-index of 5 on several regions that cause the grid to fly on top of the polymer-start-kit's headers... Is there some underlying reason for these z-index?

Selectors I found:
  .v-grid-tablewrapper.v-grid = 5
  .v-grid-scroller.v-grid = 1
  .v-grid-header-deco.v-grid = 1

Note: This may be a short coming in Polymer by not defining some clearly delineated z-index boundaries such as Modals should start at: 1000 tooltips: 500 etc etc... but I would hope this could be solved without a basic example the start-kit requiring custom z-indexes for things just to work as expected.

**Comment by tomivirkki** [comment] 2015-08-17 07:30
This is a duplicate of a ticket from last week (#79). The fix will be included in the next release.

**Closed by tomivirkki** 2015-08-17 07:30 UTC
